apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.0.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      image: ttl.sh/strimzi-connect-example-4.0.0:24h
    plugins:
      - name: idcrqv1006
        artifacts:
          - type: zip
            url: http://192.168.1.48/devops-kafka/connectors/-/raw/main/rqv1006/IdcRQV1006/files/connectors/IdcRQV1006.zip?inline=false
          - type: zip
            url: http://192.168.1.48/devops-kafka/connectors/-/raw/main/rqv1006/IdcRQV1006/files/services_config/IdcRQV1006.zip